language: cpp
os: linux
dist: focal
compiler:
  - gcc
  - clang

sudo: true

install:
  - sudo apt update -qq
  # Boost
  - sudo apt install -qq libboost-all-dev
  # Qt5
  - sudo apt install -qq qt5-default

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug ../
  - cmake --build . --target miniature-octo-spoon
  - cmake -DCMAKE_BUILD_TYPE=Release ../
  - cmake --build . --target miniature-octo-spoon