language: cpp
os: linux
dist: focal
compiler:
  - gcc
  - clang

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug ../
  - cmake --build . --target miniature-octo-spoon
  - cmake -DCMAKE_BUILD_TYPE=Release ../
  - cmake --build . --target miniature-octo-spoon